enum ESteps {
  USER_REGISTER = 'USER_REGISTER',
  SET_PASSWORD = 'SET_PASSWORD',
  SETUP_PASSWORD = 'SETUP_PASSWORD',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  ACCOUNT_LINKING = 'ACCOUNT_LINKING',
}

export default ESteps;
